Repository jasonjgardner/fresh_tailwind, pull requests merged in 2023-10, with the labels that each got.

#1 feat: Build step
  .gitignore
  deno.json
  main.ts
  mod.test.ts
  mod.ts
Labels: enhancement

#2 feat: Use Tailwind config file
  _tailwind.test.ts
  _tailwind.ts
  mod.test.ts
  mod.ts
Labels: enhancement

#3 upd: README.md
  README.md
  main.ts
Labels: documentation

#5 fix: Add deps.ts for no import config
  deno.json
  deps.ts
  mod.ts
Labels: bug

#6 Using the latest version of toFileUrl
  _tailwind.ts
Labels: bug

#10 feat: Tailwind standalone CLI usage
  _tailwind.ts
  build.ts
  cli.ts
  deps.ts
  main.ts
  mod.test.ts
  mod.ts
  types.ts
Labels: enhancement

#11 upd: Installation config files
  build.ts
  cli.ts
Labels: enhancement

#13 upd: Added template links to README
  README.md
  deps.ts
Labels: documentation

#14 Update README.md
  README.md
Labels: documentation

#15 upd: AOT Render Hook
  mod.ts
Labels: enhancement

#16 fix: Do not require deno.json for CLI build
  build.ts
Labels: bug

#17 upd: Added source map / Removed hookRender
  cli.ts
  mod.ts
  types.ts
Labels: enhancement

#19 upd: Add missing types / Remove Autoprefixer
  README.md
  deps.ts
  mod.ts
  types.ts
Labels: bug, documentation

#20 fix: Exclude JIT styles from build
  mod.ts
Labels: bug

#22 fix: allow for deno.jsonc to be processed
  README.md
  cli.ts
  deps.ts
Labels: enhancement

#24 fix: Exclude JIT output during build
  _tailwind.test.ts
  build.ts
  cli.ts
  constants.ts
  deps.ts
  main.ts
  mod.test.ts
  mod.ts
  types.ts
Labels: bug

#27 upd: Better testing / Extract PostCSS process
  .vscode/settings.json
  CONTRIBUTING.md
  build.ts
  constants.ts
  mod.test.ts
  mod.ts
Labels: enhancement

#28 ci: Fixed automated testing
  .github/workflows/deno.yml
  .github/workflows/scripts/setup.ps1
  .github/workflows/scripts/setup.sh
  .gitignore
  mod.test.ts
Labels: enhancement

#29 upd: Heropattern replacement regex
  hero.ts
Labels: bug
